export enum Service {
  EXECUTE_ON_INIT = 'EXECUTE_ON_INIT',
  CONNECTION_STRING = 'CONNECTION_STRING',
  MIGRATIONS_PATH = 'MIGRATIONS_PATH',
  RABBIT_MIGRATION_EXECUTOR = 'RABBIT_MIGRATION_EXECUTOR',
}
